name: Build and Send APK

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" -type f | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Send APK via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: ${{ steps.find_apk.outputs.apk_path }}
          message: "✅ Сборка мода завершена!"
